# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.CharField(max_length=1000)),
                ('conts', models.TextField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(max_length=1500)),
                ('nome', models.CharField(max_length=1500)),
                ('temas', models.CharField(max_length=3500)),
                ('video', models.CharField(max_length=1500)),
                ('membros', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sala'),
        ),
    ]
